import { i18n } from './i18n.svelte.js';

// UI chrome strings (not content — content lives in the JSON data as { vi, en }).
const UI = {
  vi: {
    intro: 'Giới thiệu',
    explore: 'Khám phá',
    tours: 'Tuyến',
    passport: 'Hộ chiếu',
    sites_count: (n) => `${n} địa điểm trong phố cổ`,
    all: 'Tất cả',
    no_sites: 'Chưa có điểm đến trong mục này.',
    how_it_works: 'Cách hoạt động',
    open_map: '🗺️ Khám phá bản đồ',
    see_tours: '🚶 Xem tuyến đi bộ',
    collected: (a, b) => `Bạn đã sưu tầm ${a}/${b} tem.`,
    view_passport: 'Xem hộ chiếu →',
    directions: '➤ Chỉ đường bằng Google Maps',
    checkin: '📍 Check-in tại đây',
    simulate: '🧪 Giả lập đã đến nơi (test)',
    locating: 'Đang xác định vị trí…',
    retry: 'Thử lại',
    far: (d, r) => `Bạn đang cách điểm đến khoảng ${d} m (cần ≤ ${r} m). Hãy đến gần hơn rồi thử lại.`,
    geo_denied: 'Bạn cần cho phép truy cập vị trí để check-in.',
    geo_fail: 'Không lấy được vị trí. Hãy thử lại ở ngoài trời.',
    arrived: '✔ Đã đến nơi! Trả lời câu hỏi để nhận tem:',
    question_of: (i, n) => `Câu ${i}/${n}`,
    checkin_done: '✅ Đã check-in! Tem đã được thêm vào hộ chiếu.',
    tours_title: 'Tuyến đi bộ',
    tours_sub: 'Khám phá phố cổ theo chủ đề',
    stops: (n) => `${n} điểm dừng`,
    route: 'Lộ trình',
    passport_title: 'Hộ chiếu của tôi',
    stamps_of: (a, b) => `${a}/${b} tem đã sưu tầm`,
    all_done: '🎉 Hoàn thành! Bạn đã check-in tất cả điểm đến.',
    set_complete: 'Đã hoàn thành bộ tem này!',
    redeem: '🎁 Đổi voucher',
    redeem_intro: 'Đưa màn hình này cho kiểm soát viên tại quầy vé để nhận voucher giấy.',
    staff_confirm: 'Kiểm soát viên xác nhận',
    enter_code: 'Nhập mã kiểm soát viên',
    wrong_code: 'Mã không đúng.',
    staff_only: 'Khu vực dành cho ban tổ chức. Nhập mã để xem.',
    redeemed: '✅ Đã đổi voucher. Cảm ơn bạn!',
    wrong_wait: (n) => `Chưa đúng. Đọc lại bảng giới thiệu và thử lại sau ${n} giây.`,
    keep_code: '📸 Chụp màn hình mã này! Đây là cách duy nhất lấy lại hộ chiếu nếu bạn đổi máy hoặc xoá dữ liệu trình duyệt.',
    install: '⬇️ Tải app về máy (dùng offline)',
    install_why: 'Cài về màn hình chính để dùng khi không có mạng.',
    install_ios: 'Trên iPhone: bấm nút Chia sẻ ⬆️ rồi chọn "Thêm vào MH chính".',
    // location & ticket counters
    locate_me: 'Vị trí của tôi',
    locating_now: 'Đang tìm vị trí…',
    you_are_here: 'Bạn đang ở đây',
    accuracy_m: (n) => `sai số ~${n} m`,
    booth_find: '🎟️ Quầy vé gần nhất',
    booth_hint: 'Đổi voucher hoặc nhờ hỗ trợ tại quầy vé.',
    booth_nearest: (name, d) => `Quầy ${name} · cách ${d}`,
    booth_dir: '➤ Chỉ đường tới quầy',

    org_events: 'Sự kiện khác',
    org_flagged: 'Hộ chiếu cần xem lại',
    org_flagged_none: 'Chưa có hộ chiếu nào bất thường.',
    org_flagged_hint: 'Dấu hiệu di chuyển bất khả thi giữa các điểm. Chỉ để tham khảo — vẫn phát voucher nếu khách hợp lý.',
    flag_warn: '⚠️ Hộ chiếu này có dấu hiệu check-in bất thường. Hỏi khách vài câu về điểm đến trước khi phát voucher — nếu hợp lý thì vẫn phát bình thường.',

    // scoring & rewards
    points: 'điểm',
    earned: (n) => `+${n} điểm`,
    perfect_bonus: 'Đúng hết ngay lần đầu',
    spotlight: 'Điểm cần khám phá',
    spotlight_hint: (n) => `Đang ít khách — check-in tại đây được +${n} điểm thưởng.`,
    rank: 'Danh hiệu',
    no_rank: 'Chưa có danh hiệu',
    next_rank: (n, name) => `Còn ${n} điểm nữa để đạt “${name}”`,
    rewards_title: 'Phần thưởng',
    reward_locked: (n) => `Cần ${n} điểm`,
    reward_ready: 'Đã mở khoá — nhận tại quầy vé',
    reward_taken: 'Đã nhận',
    claim: '🎁 Nhận quà',
    score_how: 'Cách tính điểm',
    pt_stamp: 'mỗi lần check-in',
    pt_perfect: 'trả lời đúng hết ngay lần đầu',
    pt_spotlight: 'check-in tại “điểm cần khám phá”',
    pt_tour: 'hoàn thành một tuyến (đủ tem của tuyến đó)',
    pt_all: (n) => `check-in đủ cả ${n} điểm đến`,
    tally_stamps: (n) => `${n} tem đã sưu tầm`,
    tally_tours: (a, b) => `Tuyến hoàn thành ${a}/${b}`,
    tally_all: 'Thưởng đủ bộ',

    // backup & recovery
    backup_title: 'Sao lưu & khôi phục',
    backup_hint:
      'Hộ chiếu được lưu trên máy bạn. Hãy ghi lại mã này — nếu đổi điện thoại hoặc xoá dữ liệu trình duyệt, bạn dùng mã để lấy lại toàn bộ tem.',
    your_code: 'Mã khôi phục',
    copy: 'Sao chép',
    copied: 'Đã sao chép',
    copy_link: 'Sao chép link sao lưu',
    restore: 'Khôi phục từ mã khác',
    restore_do: 'Khôi phục',
    restore_ok: '✅ Đã khôi phục hộ chiếu.',
    restore_bad: 'Mã gồm 8 ký tự.',
    restore_missing: 'Không tìm thấy hộ chiếu với mã này.',
    restore_offline: 'Chưa kết nối được máy chủ. Thử lại khi có mạng.',
    offline_ok: 'Mất mạng vẫn check-in được — dữ liệu tự gửi lên khi có kết nối lại.',
    ticket_points: 'Điểm bán vé',

    // tours & map
    walk: (d, m) => `${d} · ~${m} phút đi bộ`,
    open_tour: 'Xem chi tiết tuyến →',
    map_street: 'Bản đồ',
    map_sat: 'Vệ tinh',
    popup_detail: 'Xem & check-in',
    popup_dir: 'Chỉ đường',
    stamped: 'Đã check-in',
    open_now: 'Đang mở',
    closed_now: 'Đã đóng cửa',
    closing_soon: (m) => `Sắp đóng · còn ${m} phút`,
    opens_at: (t) => `Mở lúc ${t}`,
    filter_open: 'Đang mở',
    closed_warning: 'Điểm này đang đóng cửa — bạn vẫn check-in được nếu đứng đúng vị trí.',

    // organizer dashboard
    org_title: 'Bảng điều hành',
    org_sub: 'Dữ liệu check-in theo điểm đến',
    org_evenness: 'Độ đồng đều',
    org_total: 'Lượt check-in',
    org_covered: 'Điểm có khách',
    org_spotlight_now: 'Đang được thưởng điểm',
    org_refresh: 'Tải lại',
    org_export: '⬇ Tải CSV',
    org_no_data: 'Chưa có lượt check-in nào. Số liệu hiện ra ngay khi có người check-in đầu tiên.',
    org_survey: 'Toạ độ cần khảo sát lại',
    org_quiz_todo: 'Bộ câu hỏi còn tự sinh',
    org_nearest_ticket: 'Quầy vé gần nhất',
    org_traffic: 'Lượng khách (khảo sát)',
    org_priority: 'Ưu tiên quảng bá',
    lvl_low: 'thấp',
    lvl_medium: 'trung bình',
    lvl_high: 'cao',
    org_updated: (t) => `Cập nhật lúc ${t}`,

    // content editor (organizer tier only)
    org_tier_volunteer: 'Tình nguyện viên (chỉ xem)',
    org_tier_admin: 'Ban tổ chức (sửa được nội dung)',
    org_edit: 'Sửa nội dung',
    org_edit_hint:
      'Sửa ở đây rồi bấm tải file JSON về và gửi cho kỹ thuật thay vào src/lib/data/. Không lưu thẳng lên máy chủ — sửa xong mà không tải file là mất.',
    org_need_admin: 'Cần mã ban tổ chức để sửa nội dung. Mã tình nguyện viên chỉ xem được số liệu.',
    org_tab_dest: 'Điểm đến',
    org_tab_tours: 'Tuyến',
    org_tab_rewards: 'Phần thưởng',
    org_tab_event: 'Giới thiệu',
    org_tours_hint:
      'Thứ tự điểm dừng chính là thứ tự đi bộ. Mỗi điểm đến chỉ được thuộc một tuyến, và mọi điểm đến đều phải nằm trong một tuyến nào đó.',
    org_rewards_hint: (n) => `Mốc điểm phải tăng dần và không vượt quá ${n} điểm (mức tối đa chắc chắn đạt được).`,
    org_event_hint: 'Nội dung trang chủ.',
    org_add_tour: '+ Thêm tuyến',
    org_del_tour: 'Xoá tuyến',
    org_add_stop: '+ Thêm điểm dừng',
    org_add_tier: '+ Thêm mốc',
    org_del_tier: 'Xoá mốc',
    org_add_step: '+ Thêm bước',
    org_del_step: 'Xoá bước',
    org_download_json: (f) => `⬇ Tải ${f}`,
    org_load_json: 'Mở file đã sửa',
    org_reset: 'Về bản gốc',
    org_reset_confirm: 'Bỏ hết thay đổi chưa tải về?',
    org_problems: (n) => `${n} lỗi — sửa hết rồi mới tải file về`,
    org_data_ok: '✔ Dữ liệu hợp lệ',
    org_bad_file: (m) => `Không đọc được file: ${m}`,
    org_add_q: '+ Thêm câu hỏi',
    org_del_q: 'Xoá câu',
    org_add_opt: '+ Thêm đáp án',
    org_del_opt: 'Xoá',
    org_answer: 'Đáp án đúng',
    org_generated: 'tự sinh',
    org_reviewed: 'Đã kiểm tra',
    org_needs_survey: 'Toạ độ cần khảo sát',
    f_code: 'Mã',
    f_name: 'Tên',
    f_address: 'Địa chỉ',
    f_hours: 'Giờ mở cửa',
    f_desc: 'Giới thiệu',
    f_category: 'Nhóm',
    f_radius: 'Bán kính (m)',
    f_question: 'Câu hỏi',
    f_difficulty: 'Độ khó',
    f_title: 'Tiêu đề',
    f_theme: 'Chủ đề',
    f_voucher: 'Quà tặng',
    f_stops: 'Điểm dừng',
    f_stamps: 'Số tem',
    f_points: 'Điểm',
    f_icon: 'Biểu tượng',
    f_reward: 'Phần thưởng',
    f_subtitle: 'Phụ đề',
    f_dates: 'Thời gian',
    f_intro: 'Giới thiệu',
    f_note: 'Ghi chú',
    f_steps: 'Các bước',
    stamps_at: (n) => `từ ${n} điểm`,
    org_details: 'Chi tiết',
    lvl_easy: 'dễ',
    lvl_hard: 'khó'
  },
  en: {
    intro: 'About',
    explore: 'Explore',
    tours: 'Tours',
    passport: 'Passport',
    sites_count: (n) => `${n} sites in the Ancient Town`,
    all: 'All',
    no_sites: 'No sites in this category yet.',
    how_it_works: 'How it works',
    open_map: '🗺️ Explore the map',
    see_tours: '🚶 Walking tours',
    collected: (a, b) => `You have collected ${a}/${b} stamps.`,
    view_passport: 'View passport →',
    directions: '➤ Directions in Google Maps',
    checkin: '📍 Check in here',
    simulate: '🧪 Simulate arrival (test)',
    locating: 'Locating you…',
    retry: 'Try again',
    far: (d, r) => `You are about ${d} m away (need ≤ ${r} m). Get closer and try again.`,
    geo_denied: 'Please allow location access to check in.',
    geo_fail: 'Could not get your location. Try again outdoors.',
    arrived: '✔ You are here! Answer the questions to earn a stamp:',
    question_of: (i, n) => `Question ${i}/${n}`,
    checkin_done: '✅ Checked in! The stamp was added to your passport.',
    tours_title: 'Walking tours',
    tours_sub: 'Explore the old town by theme',
    stops: (n) => `${n} stops`,
    route: 'Route',
    passport_title: 'My passport',
    stamps_of: (a, b) => `${a}/${b} stamps collected`,
    all_done: '🎉 Complete! You have checked in everywhere.',
    set_complete: 'You completed this stamp set!',
    redeem: '🎁 Redeem voucher',
    redeem_intro: 'Show this screen to a staff member at any ticket counter to receive a paper voucher.',
    staff_confirm: 'Staff confirm',
    enter_code: 'Enter staff code',
    wrong_code: 'Wrong code.',
    staff_only: 'Organizer area. Enter the staff code to continue.',
    redeemed: '✅ Voucher redeemed. Thank you!',
    wrong_wait: (n) => `Not quite. Read the sign again and retry in ${n}s.`,
    keep_code: '📸 Screenshot this code! It is the only way to get your passport back on a new phone or after clearing your browser.',
    install: '⬇️ Install the app (works offline)',
    install_why: 'Add it to your home screen to use it without a signal.',
    install_ios: 'On iPhone: tap Share ⬆️ then "Add to Home Screen".',
    // location & ticket counters
    locate_me: 'My location',
    locating_now: 'Finding you…',
    you_are_here: 'You are here',
    accuracy_m: (n) => `±${n} m`,
    booth_find: '🎟️ Nearest ticket counter',
    booth_hint: 'Claim vouchers or ask for help at a ticket counter.',
    booth_nearest: (name, d) => `Counter ${name} · ${d} away`,
    booth_dir: '➤ Directions to the counter',

    org_events: 'Other events',
    org_flagged: 'Passports to review',
    org_flagged_none: 'Nothing unusual so far.',
    org_flagged_hint: 'Stamps that could not have been walked between. Advisory only — hand over the voucher if the visitor makes sense.',
    flag_warn: '⚠️ This passport has unusual check-in timing. Ask the visitor about a site or two before handing over the voucher — if they check out, redeem as normal.',

    // scoring & rewards
    points: 'points',
    earned: (n) => `+${n} points`,
    perfect_bonus: 'All correct first try',
    spotlight: 'Spotlight site',
    spotlight_hint: (n) => `Quiet right now — checking in here earns +${n} bonus points.`,
    rank: 'Rank',
    no_rank: 'No rank yet',
    next_rank: (n, name) => `${n} more points to reach “${name}”`,
    rewards_title: 'Rewards',
    reward_locked: (n) => `Needs ${n} points`,
    reward_ready: 'Unlocked — collect at any ticket counter',
    reward_taken: 'Collected',
    claim: '🎁 Claim',
    score_how: 'How points work',
    pt_stamp: 'per check-in',
    pt_perfect: 'quiz answered correctly first try',
    pt_spotlight: 'checking in at a spotlight site',
    pt_tour: 'completing a tour (every stamp on it)',
    pt_all: (n) => `checking in at all ${n} sites`,
    tally_stamps: (n) => `${n} stamps collected`,
    tally_tours: (a, b) => `Tours completed ${a}/${b}`,
    tally_all: 'Full-set bonus',

    // backup & recovery
    backup_title: 'Backup & recovery',
    backup_hint:
      'Your passport is stored on this device. Note this code down — if you switch phones or clear your browser, it brings every stamp back.',
    your_code: 'Recovery code',
    copy: 'Copy',
    copied: 'Copied',
    copy_link: 'Copy backup link',
    restore: 'Restore from another code',
    restore_do: 'Restore',
    restore_ok: '✅ Passport restored.',
    restore_bad: 'The code is 8 characters.',
    restore_missing: 'No passport found for that code.',
    restore_offline: 'Could not reach the server. Try again when online.',
    offline_ok: 'Check-in works offline — your data uploads once you are back online.',
    ticket_points: 'Ticket counters',

    // tours & map
    walk: (d, m) => `${d} · ~${m} min walk`,
    open_tour: 'Open tour →',
    map_street: 'Map',
    map_sat: 'Satellite',
    popup_detail: 'Open & check in',
    popup_dir: 'Directions',
    stamped: 'Checked in',
    open_now: 'Open now',
    closed_now: 'Closed',
    closing_soon: (m) => `Closing in ${m} min`,
    opens_at: (t) => `Opens ${t}`,
    filter_open: 'Open now',
    closed_warning: 'This site is closed right now — you can still check in if you are at the spot.',

    // organizer dashboard
    org_title: 'Organizer dashboard',
    org_sub: 'Check-ins per destination',
    org_evenness: 'Evenness',
    org_total: 'Check-ins',
    org_covered: 'Sites visited',
    org_spotlight_now: 'Currently bonus-boosted',
    org_refresh: 'Refresh',
    org_export: '⬇ Export CSV',
    org_no_data: 'No check-ins yet. Numbers appear as soon as the first visitor checks in.',
    org_survey: 'Coordinates to re-survey',
    org_quiz_todo: 'Quiz banks still auto-generated',
    org_nearest_ticket: 'Nearest counter',
    org_traffic: 'Footfall (survey)',
    org_priority: 'Promo priority',
    lvl_low: 'low',
    lvl_medium: 'medium',
    lvl_high: 'high',
    org_updated: (t) => `Updated ${t}`,

    // content editor (organizer tier only)
    org_tier_volunteer: 'Volunteer (view only)',
    org_tier_admin: 'Organizer (can edit content)',
    org_edit: 'Edit content',
    org_edit_hint:
      'Edit here, download the JSON and hand it to the dev to replace src/lib/data/. Nothing is saved to the server — edits are lost if you do not download.',
    org_need_admin: 'Editing content needs the organizer code. The volunteer code can only read the numbers.',
    org_tab_dest: 'Destinations',
    org_tab_tours: 'Tours',
    org_tab_rewards: 'Rewards',
    org_tab_event: 'About',
    org_tours_hint:
      'Stop order is the walking order. Each destination belongs to exactly one tour, and every destination must be in one.',
    org_rewards_hint: (n) => `Point thresholds must ascend and cannot exceed ${n}, the score every visitor can be sure of reaching.`,
    org_event_hint: 'Home page copy.',
    org_add_tour: '+ Add tour',
    org_del_tour: 'Delete tour',
    org_add_stop: '+ Add stop',
    org_add_tier: '+ Add tier',
    org_del_tier: 'Delete tier',
    org_add_step: '+ Add step',
    org_del_step: 'Delete step',
    org_download_json: (f) => `⬇ Download ${f}`,
    org_load_json: 'Open an edited file',
    org_reset: 'Back to shipped version',
    org_reset_confirm: 'Discard every change you have not downloaded?',
    org_problems: (n) => `${n} problems — fix them before downloading`,
    org_data_ok: '✔ Data is valid',
    org_bad_file: (m) => `Could not read that file: ${m}`,
    org_add_q: '+ Add question',
    org_del_q: 'Delete',
    org_add_opt: '+ Add option',
    org_del_opt: 'Remove',
    org_answer: 'Correct answer',
    org_generated: 'auto-generated',
    org_reviewed: 'Mark reviewed',
    org_needs_survey: 'Coordinates need a survey',
    f_code: 'Code',
    f_name: 'Name',
    f_address: 'Address',
    f_hours: 'Opening hours',
    f_desc: 'Description',
    f_category: 'Category',
    f_radius: 'Radius (m)',
    f_question: 'Question',
    f_difficulty: 'Difficulty',
    f_title: 'Title',
    f_theme: 'Theme',
    f_voucher: 'Voucher',
    f_stops: 'Stops',
    f_stamps: 'Stamps',
    f_points: 'Points',
    f_icon: 'Icon',
    f_reward: 'Reward',
    f_subtitle: 'Subtitle',
    f_dates: 'Dates',
    f_intro: 'Intro',
    f_note: 'Note',
    f_steps: 'Steps',
    stamps_at: (n) => `from ${n} points`,
    org_details: 'Details',
    lvl_easy: 'easy',
    lvl_hard: 'hard'
  }
};

export function s(key, ...args) {
  const v = UI[i18n.lang]?.[key] ?? UI.vi[key] ?? key;
  return typeof v === 'function' ? v(...args) : v;
}
