import { i18n } from './i18n.svelte.js';

// UI chrome strings (not content — content lives in the JSON data as { vi, en }).
const UI = {
  vi: {
    intro: 'Giới thiệu',
    explore: 'Khám phá',
    tours: 'Tuyến tham quan',
    passport: 'Sổ tay',
    sites_count: (n) => `${n} địa điểm trong phố cổ`,
    all: 'Tất cả',
    no_sites: 'Chưa có điểm đến trong mục này.',
    journey: 'Hành trình',
    how_it_works: 'Cách hoạt động',
    open_map: '🗺️ Khám phá bản đồ',
    see_tours: '🚶 Xem tuyến đi bộ',
    collected: (a, b) => `Bạn đã sưu tầm ${a}/${b} tem.`,
    view_passport: 'Xem sổ tay →',
    directions: 'Chỉ đường bằng Google Maps',
    checkin: 'Check-in tại đây',
    simulate: '🧪 Giả lập đã đến nơi (test)',
    locating: 'Đang xác định vị trí…',
    retry: 'Thử lại',
    back: 'Quay lại',
    far: (d, r) => `Bạn đang cách điểm đến khoảng ${d} m (cần ≤ ${r} m). Hãy đến gần hơn rồi thử lại.`,
    geo_denied: 'Bạn cần cho phép truy cập vị trí để check-in.',
    geo_fail: 'Không lấy được vị trí. Hãy thử lại ở ngoài trời.',
    arrived: '✔ Đã đến nơi! Trả lời câu hỏi để nhận tem:',
    highlights: 'Đừng bỏ lỡ',
    quiz_continue: 'Tiếp tục →',
    correct_title: 'Chính xác!',
    wrong_title: 'Chưa đúng',
    nav_start: 'Bắt đầu di chuyển',
    nav_close: 'Đóng',
    nav_next: 'Điểm tiếp theo',
    nav_arrived: 'Bạn đã tới nơi',
    nav_here: 'Check in tại đây →',
    nav_locate_prompt: 'Bật định vị để được dẫn đường',
    nav_done: 'Đã đi hết tuyến 🎉',
    nav_stops_left: (n) => `còn ${n} điểm`,
    nav_headingup: 'Xoay bản đồ theo hướng đi',
    question_of: (i, n) => `Câu ${i}/${n}`,
    checkin_done: 'Đã check-in. Tem đã vào sổ tay của bạn.',
    tours_title: 'Tuyến đi bộ',
    tours_sub: 'Khám phá phố cổ theo chủ đề',
    stops: (n) => `${n} điểm dừng`,
    route: 'Lộ trình',

    // planner ("choose your 5")
    plan: 'Gợi ý',
    plan_title: 'Chọn điểm đến',
    plan_sub: 'Vé của bạn gồm 5 điểm. Chọn một bộ hợp sở thích và hợp thời tiết.',
    plan_cta: '🧭 Gợi ý giúp tôi 5 điểm',
    weather_q: 'Thời tiết hiện tại thế nào?',
    w_hot: '☀️ Nắng',
    w_mild: '🌤️ Dịu mát',
    w_rain: '🌧️ Mưa',
    taste_q: 'Bạn thích gì?',
    plan_top: 'Gợi ý hôm nay',
    plan_alts: 'Lựa chọn khác',
    go_route: 'Di chuyển theo tuyến này',
    reason_quiet: 'Không đông đúc',
    reason_sun: 'Hợp trời nóng',
    reason_rain: 'Tránh mưa',
    reason_open: 'Đang mở cửa',
    reason_walk: (m) => `~${m}′`,
    cls_monument: 'di tích',
    cls_museum: 'bảo tàng',
    cls_free: 'tự do',
    comp_line: (a, b, c) => `${a} di tích · ${b} bảo tàng · ${c} tự do`,
    plan_none: 'Không có bộ điểm nào khớp với bộ lọc.',
    plan_scan: 'Đã có vé? Quét để lưu',
    scan_btn: 'Quét vé',
    scan_saved: '✓ Đã lưu vé',
    buy_ticket: 'Mua vé ở đâu?',
    show_on_map: 'Xem quầy vé trên bản đồ',
    scan_close: 'Đóng',
    scan_point: 'Đưa mã QR trên vé vào khung',
    scan_unsupported: 'Không mở được camera. Hãy cho phép dùng camera, hoặc bỏ qua và chọn bộ điểm bên dưới.',
    scan_bad_ticket: 'Đây không phải mã QR trên vé Hội An. Hãy quét đúng mã in trên vé của bạn.',
    welcome_sub: 'Người bạn đồng hành trong hành trình tham quan phố cổ.',
    welcome_start: 'Bắt đầu',
    scan_step: 'Bước 1',
    scan_title: 'Quét mã vé',
    scan_why: 'Quét mã QR trên vé để lưu lại hành trình tham quan và đồng bộ khi bạn đổi thiết bị.',
    scan_skip: 'Bỏ qua, chọn điểm đến ngay',
    scan_continue: 'Tiếp tục',
    terms_pre: 'Khi tiếp tục, bạn đồng ý với ',
    terms_link: 'điều khoản sử dụng',
    terms_post: ' của chúng tôi.',
    terms_title: 'Điều khoản sử dụng',
    perm_gps: 'Vị trí: điểm danh và tìm quầy vé gần nhất.',
    perm_motion: 'Chuyển động: la bàn chỉ hướng khi đi bộ.',
    perm_title: 'Vị trí và chuyển động',
    your_ticket: 'Vé của bạn',
    route_label: 'Tuyến của bạn',
    route_empty: 'Chưa có tuyến, chọn 5 điểm',
    all_sites: 'Tất cả điểm',
    r_unlocked: 'Đã mở',
    r_locked: 'Chưa mở',
    pick_one: 'chọn 1',
    view_mode: 'Chế độ xem',
    view_list: 'Danh sách',
    view_map: 'Bản đồ',
    step_monument: 'Di tích',
    step_museum: 'Bảo tàng',
    step_free: '3 điểm tự do',
    recommend_full: '✦ Gợi ý cả bộ 5 cho tôi',
    rec_head: 'Gợi ý cho bạn',
    rec_sub: 'Bộ 5 điểm dựng sẵn, hợp lệ, xếp theo thời tiết & giờ mở cửa. Dùng luôn, hoặc tự chọn.',
    rec_badge: 'Đề xuất',
    use_set: 'Dùng bộ này',
    pick_own: 'Tự chọn 5 điểm',
    back_sugg: '← Xem gợi ý',
    reset_picks: '↺ Xoá hết',
    walk_time: (m) => `${m} phút đi bộ`,
    open_all: 'Cả 5 đang mở',
    n_closed: (n) => `${n} điểm đang đóng`,
    quiet_pick: 'Có điểm vắng khách',
    all_cats: 'Tất cả',
    route_walk: (d, m) => `${d} · ${m} phút đi bộ`,
    auto_free: 'Chọn giúp tôi 3 điểm còn lại',
    list_more: (n) => `Xem thêm ${n} điểm`,
    rank_dist: 'Sắp xếp theo khoảng cách',
    pick_do: 'Chọn',
    pick_remove: 'Bỏ chọn',
    picked_lbl: '✓ Đã chọn',
    build_done: 'Tiếp tục',
    done_title: 'Hành trình của bạn',
    done_sub: 'Đi tới từng điểm và check-in để đóng dấu.',
    go_checkin: 'Lên đường!',
    edit_plan: 'Chọn lại',
    passport_title: 'Sổ tay của tôi',
    lang_switch: 'Ngôn ngữ',
    code_label: 'Mã vé của bạn',
    stamps_of: (a, b) => `${a}/${b} tem đã sưu tầm`,
    all_done: '🎉 Hoàn thành! Bạn đã check-in tất cả điểm đến.',
    set_complete: 'Đã hoàn thành bộ tem này!',
    redeem: '🎁 Đổi voucher',
    redeem_intro: 'Đưa màn hình này cho nhân viên tại quầy vé để nhận voucher giấy.',
    staff_confirm: 'Nhân viên xác nhận',
    enter_code: 'Nhập mã nhân viên',
    wrong_code: 'Mã không đúng.',
    staff_only: 'Khu vực dành cho ban tổ chức. Nhập mã để xem.',
    redeemed: '✅ Đã đổi voucher. Cảm ơn bạn!',
    wrong_wait: (n) => `Chưa đúng. Đọc lại bảng giới thiệu và thử lại sau ${n} giây.`,
    keep_code: 'Hãy chụp lại mã này. Đây là cách duy nhất lấy lại sổ tay nếu bạn đổi thiết bị hoặc xoá dữ liệu trình duyệt.',
    install: '⬇️ Tải app về máy (dùng offline)',
    install_why: 'Cài về màn hình chính để dùng khi không có mạng.',
    install_ios: 'Trên iPhone: bấm nút Chia sẻ ⬆️ rồi chọn "Thêm vào Màn hình chính".',
    // location & ticket counters
    locate_me: 'Vị trí của tôi',
    reset_north: 'Xoay về hướng Bắc',
    research_optin: 'Chia sẻ số lượng tham quan ẩn danh (không lưu lộ trình, thời gian hay danh tính cá nhân). Chạm để bật/tắt.',
    journey_optin: 'Tham gia nghiên cứu hành trình (tùy chọn): ghi lại thứ tự các điểm bạn ghé trong một lần tham quan, ẩn danh, để so sánh lộ trình theo quốc tịch. Chạm để tham gia.',
    loc_note: '📍 Vị trí và la bàn dùng để hiện bạn đang ở đâu và quay về hướng nào, giúp điểm danh và tìm quầy vé gần nhất. Ứng dụng sẽ xin phép khi bạn mở bản đồ.',
    study_note: 'Ngoài ra, hệ thống tự động ghi nhận số lượng người tham quan ẩn danh để ban tổ chức điều phối khách hợp lý giữa các điểm.',
    hours_label: 'Giờ mở',
    addr_label: 'Địa chỉ',
    prev_site: 'Điểm trước',
    next_site: 'Điểm sau',
    locating_now: 'Đang xác định vị trí…',
    booth_find: '🎟️ Quầy vé gần nhất',
    booth_hint: 'Đổi voucher hoặc nhờ hỗ trợ tại quầy vé.',
    booth_nearest: (name, d) => `Quầy ${name} · cách ${d}`,
    booth_dir: '➤ Chỉ đường tới quầy',

    org_heat: 'Bản đồ nhiệt (nghiên cứu)',
    org_heat_hint: 'Dữ liệu mật độ được ẩn danh hoá từ người dùng đã đồng ý chia sẻ vị trí. Chỉ đếm theo ô ~150 m, không lưu lộ trình; ô dưới 5 lượt được ẩn.',
    org_heat_filter: 'Lọc theo quốc tịch:',
    org_heat_all: 'Tất cả',
    org_lang: 'Ngôn ngữ / quốc tịch',
    org_lang_hint: 'Quốc tịch được ước lượng qua ngôn ngữ thiết bị và ngôn ngữ khách chọn ở màn hình chào.',
    org_lang_device: 'Ngôn ngữ thiết bị',
    org_lang_pick: 'Ngôn ngữ đã chọn',
    org_nat: 'Hành vi theo quốc tịch',
    org_nat_hint: 'Số lượt (ẩn danh) cho từng hành vi, chia theo ngôn ngữ khách chọn. Hàng = điểm/bước, cột = quốc tịch.',
    org_nat_metric: 'Chỉ số',
    org_nat_none: 'Chưa có dữ liệu theo quốc tịch.',
    org_journeys: 'Hành trình (nghiên cứu, tùy chọn)',
    org_journeys_hint: 'Thứ tự ghé điểm theo từng lần tham quan, chỉ từ khách đã đồng ý tham gia. Mỗi phiên là một mã tạm thời, không liên kết giữa các lần.',
    org_journeys_export: '⬇ Tải hành trình (CSV)',
    org_journeys_count: (n) => `${n} sự kiện hành trình đã ghi`,
    org_events: 'Sự kiện khác',
    org_flagged: 'Sổ tay cần xem lại',
    org_flagged_none: 'Chưa có sổ tay nào bất thường.',
    org_flagged_hint: 'Có dấu hiệu di chuyển giữa các điểm nhanh hơn mức có thể.',
    flag_warn: '⚠️ Sổ tay này có dấu hiệu check-in bất thường. Hỏi khách vài câu về điểm đến trước khi phát voucher. Nếu hợp lý thì vẫn phát bình thường.',

    // scoring & rewards
    points: 'điểm',
    earned: (n) => `+${n} điểm`,
    perfect_bonus: 'Đúng hết ngay lần đầu',
    spotlight: 'Điểm cần khám phá',
    spotlight_hint: (n) => `Tiêu điểm hiện tại. Check-in tại đây được +${n} điểm thưởng.`,
    rank: 'Danh hiệu',
    no_rank: 'Chưa có danh hiệu',
    next_rank: (n, name) => `Còn ${n} điểm nữa để đạt “${name}”`,
    rewards_title: 'Phần thưởng',
    reward_locked: (n) => `Cần ${n} điểm`,
    reward_ready: 'Đã mở khoá. Nhận tại quầy vé',
    reward_taken: 'Đã nhận',
    other_sites: 'Điểm tham quan khác',
    other_sites_hint: 'Vẫn nhận tem và điểm, không thuộc tuyến nào',
    claim: '🎁 Nhận quà',
    score_how: 'Cách tính điểm',
    pt_stamp: 'mỗi lần check-in',
    pt_perfect: 'trả lời đúng hết ngay lần đầu',
    pt_spotlight: 'check-in tại “điểm cần khám phá”',
    pt_tour: 'hoàn thành một tuyến (đủ tem của tuyến đó)',
    pt_all: (n) => `check-in đủ cả ${n} điểm đến`,
    tally_stamps: (n) => `đã sưu tầm ${n} tem`,
    tally_tours: (a, b) => `Tuyến hoàn thành ${a}/${b}`,
    tally_all: 'đủ bộ phần thưởng',

    // backup & recovery
    backup_title: 'Sao lưu & khôi phục',
    backup_hint:
      'Sổ tay được lưu trên thiết bị của bạn. Hãy ghi lại mã này. Nếu đổi điện thoại hoặc xoá dữ liệu trình duyệt, bạn có thể dùng mã này để lấy lại toàn bộ tem.',
    your_code: 'Mã khôi phục',
    copy: 'Sao chép',
    copied: 'Đã sao chép',
    copy_link: 'Sao chép link sao lưu',
    restore: 'Khôi phục từ mã khác',
    restore_do: 'Khôi phục',
    restore_ok: '✅ Đã khôi phục sổ tay.',
    restore_bad: 'Mã gồm 8 ký tự.',
    restore_missing: 'Không tìm thấy sổ tay với mã này.',
    restore_offline: 'Chưa kết nối được máy chủ. Thử lại khi có mạng.',
    offline_ok: 'Mất mạng vẫn check-in được. Dữ liệu tự gửi lên khi có kết nối lại.',
    ticket_points: 'Điểm bán vé',
    show_all_sites: 'Xem tất cả điểm đến',

    // tours & map
    walk: (d, m) => `${d} · ~${m} phút đi bộ`,
    open_tour: 'Xem chi tiết tuyến →',
    popup_detail: 'Xem & check-in',
    popup_dir: 'Chỉ đường',
    stamped: 'Đã check-in',
    open_now: 'Đang mở cửa',
    closed_now: 'Đã đóng cửa',
    closing_soon: (m) => `Sắp đóng cửa trong ${m} phút`,
    opens_at: (t) => `Mở lúc ${t}`,
    filter_open: 'Đang mở cửa',
    closed_warning: 'Điểm này đang đóng cửa. Bạn vẫn check-in được nếu đứng đúng vị trí.',

    // organizer dashboard
    org_title: 'Bảng điều hành',
    org_sub: 'Dữ liệu check-in theo điểm đến',
    org_evenness: 'Độ đồng đều',
    org_total: 'Lượt check-in',
    org_covered: 'Điểm có khách',
    org_spotlight_now: 'Đang được thưởng điểm',
    org_refresh: 'Tải lại',
    org_export: '⬇ Tải CSV',
    org_no_data: 'Chưa có lượt check-in nào. Số liệu hiện ra ngay khi có người check-in đầu tiên.',
    org_survey: 'Toạ độ cần khảo sát lại',
    org_quiz_todo: 'Bộ câu hỏi còn tự sinh',
    org_nearest_ticket: 'Quầy vé gần nhất',
    org_traffic: 'Lượng khách (khảo sát)',
    org_priority: 'Ưu tiên quảng bá',
    lvl_low: 'thấp',
    lvl_medium: 'trung bình',
    lvl_high: 'cao',
    org_updated: (t) => `Cập nhật lúc ${t}`,

    // content editor (organizer tier only)
    org_tier_volunteer: 'Tình nguyện viên (chỉ xem)',
    org_tier_admin: 'Ban tổ chức (sửa được nội dung)',
    org_edit: 'Sửa nội dung',
    org_edit_hint:
      'Sửa tại đây rồi bấm tải file JSON về và gửi cho bộ phận kỹ thuật để cập nhật vào src/lib/data/. Không lưu thẳng lên máy chủ. File sẽ mất nếu sửa xong nhưng không tải về.',
    org_need_admin: 'Cần mã ban tổ chức để sửa nội dung. Mã tình nguyện viên chỉ xem được số liệu.',
    org_tab_dest: 'Điểm đến',
    org_tab_tours: 'Tuyến',
    org_tab_rewards: 'Phần thưởng',
    org_tab_event: 'Giới thiệu',
    org_tours_hint:
      'Hành trình được sắp xếp theo đúng thứ tự các điểm đến. Mỗi điểm đến chỉ được thuộc một tuyến; điểm không nằm trong tuyến nào vẫn nhận tem và điểm thưởng, chỉ là không tạo thành bộ quà tặng.',
    org_rewards_hint: (n) => `Mốc điểm phải tăng dần và không vượt quá ${n} điểm (mức điểm tối đa mà người chơi chắc chắn đạt được).`,
    org_event_hint: 'Nội dung trang chủ.',
    org_add_tour: '+ Thêm tuyến',
    org_del_tour: 'Xoá tuyến',
    org_add_stop: '+ Thêm điểm dừng',
    org_add_tier: '+ Thêm mốc',
    org_del_tier: 'Xoá mốc',
    org_add_step: '+ Thêm bước',
    org_del_step: 'Xoá bước',
    org_download_json: (f) => `⬇ Tải ${f}`,
    org_load_json: 'Mở file đã sửa',
    org_reset: 'Về bản gốc',
    org_reset_confirm: 'Bỏ hết thay đổi chưa tải về?',
    org_problems: (n) => `${n} lỗi - sửa hết rồi mới tải file về`,
    org_data_ok: '✔ Dữ liệu hợp lệ',
    org_bad_file: (m) => `Không đọc được file: ${m}`,
    org_add_q: '+ Thêm câu hỏi',
    org_del_q: 'Xoá câu',
    org_add_opt: '+ Thêm đáp án',
    org_del_opt: 'Xoá',
    org_answer: 'Đáp án đúng',
    org_generated: 'tự sinh',
    org_reviewed: 'Đã kiểm tra',
    org_needs_survey: 'Toạ độ cần khảo sát',
    f_code: 'Mã',
    f_name: 'Tên',
    f_address: 'Địa chỉ',
    f_hours: 'Giờ mở cửa',
    f_desc: 'Giới thiệu',
    f_category: 'Nhóm',
    f_radius: 'Bán kính (m)',
    f_question: 'Câu hỏi',
    f_difficulty: 'Độ khó',
    f_title: 'Tiêu đề',
    f_theme: 'Chủ đề',
    f_voucher: 'Quà tặng',
    f_stops: 'Điểm dừng',
    f_points: 'Điểm',
    f_icon: 'Biểu tượng',
    f_reward: 'Phần thưởng',
    f_subtitle: 'Phụ đề',
    f_tagline: 'Thông điệp',
    f_year: 'Năm',
    f_venue: 'Địa điểm',
    f_dates: 'Thời gian',
    f_intro: 'Giới thiệu',
    f_note: 'Ghi chú',
    f_steps: 'Các bước',
    org_details: 'Chi tiết',
    lvl_easy: 'dễ',
    lvl_hard: 'khó'
  },
  en: {
    intro: 'About',
    explore: 'Explore',
    tours: 'Tours',
    passport: 'Passport',
    sites_count: (n) => `${n} sites in the Ancient Town`,
    all: 'All',
    no_sites: 'No sites in this category yet.',
    journey: 'The journey',
    how_it_works: 'How it works',
    open_map: '🗺️ Explore the map',
    see_tours: '🚶 Walking tours',
    collected: (a, b) => `You have collected ${a}/${b} stamps.`,
    view_passport: 'View passport →',
    directions: 'Directions in Google Maps',
    checkin: 'Check in here',
    simulate: '🧪 Simulate arrival (test)',
    locating: 'Locating you…',
    retry: 'Try again',
    back: 'Back',
    far: (d, r) => `You are about ${d} m away (need ≤ ${r} m). Get closer and try again.`,
    geo_denied: 'Please allow location access to check in.',
    geo_fail: 'Could not get your location. Try again outdoors.',
    arrived: '✔ You are here! Answer the questions to earn a stamp:',
    highlights: "Don't miss",
    quiz_continue: 'Continue →',
    correct_title: 'Correct!',
    wrong_title: 'Not quite',
    nav_start: 'Start walking',
    nav_close: 'Close',
    nav_next: 'Next stop',
    nav_arrived: "You've arrived",
    nav_here: 'Check in here →',
    nav_locate_prompt: 'Turn on location to guide you',
    nav_done: 'Route complete 🎉',
    nav_stops_left: (n) => `${n} stop${n === 1 ? '' : 's'} left`,
    nav_headingup: 'Rotate map to my heading',
    question_of: (i, n) => `Question ${i}/${n}`,
    checkin_done: 'Checked in. The stamp is in your passport.',
    tours_title: 'Walking tours',
    tours_sub: 'Explore the old town by theme',
    stops: (n) => `${n} stops`,
    route: 'Route',

    // planner ("choose your 5")
    plan: 'Plan',
    plan_title: 'Choose your stops',
    plan_sub: 'Your ticket covers 5 sites — pick a set that fits your taste and the weather.',
    plan_cta: '🧭 Plan my 5 sites',
    weather_q: 'Weather right now?',
    w_hot: '☀️ Hot',
    w_mild: '🌤️ Mild',
    w_rain: '🌧️ Rain',
    taste_q: 'What are you into?',
    plan_top: 'Today’s pick',
    plan_alts: 'Other sets',
    go_route: 'Take this route',
    reason_quiet: 'Quieter',
    reason_sun: 'Good in heat',
    reason_rain: 'Stays dry',
    reason_open: 'All open',
    reason_walk: (m) => `~${m}′`,
    cls_monument: 'monument',
    cls_museum: 'museum',
    cls_free: 'free',
    comp_line: (a, b, c) => `${a} monument · ${b} museum · ${c} free`,
    plan_none: 'No sets match your filters.',
    plan_scan: 'Have a ticket? Scan to save',
    scan_btn: 'Scan ticket',
    scan_saved: '✓ Ticket saved',
    buy_ticket: 'Where to buy?',
    show_on_map: 'Show ticket counters on the map',
    scan_close: 'Close',
    scan_point: 'Point the ticket QR into the frame',
    scan_unsupported: 'Couldn’t open the camera — allow camera access, or skip and pick a set below.',
    scan_bad_ticket: 'That’s not a Hội An ticket QR — scan the QR printed on your ticket.',
    welcome_sub: 'Your companion for the old-town sightseeing ticket.',
    welcome_start: 'Get started',
    scan_step: 'Step 1',
    scan_title: 'Scan your ticket',
    scan_why: 'Scan the QR on your ticket to save your progress — re-scan on another phone to restore your passport.',
    scan_skip: 'Skip, choose sites now',
    scan_continue: 'Continue',
    terms_pre: 'By continuing you accept our ',
    terms_link: 'terms and conditions',
    terms_post: '.',
    terms_title: 'Terms and conditions',
    perm_gps: 'Location: to check in and find the nearest ticket counter.',
    perm_motion: 'Motion: compass heading while you walk.',
    perm_title: 'Location and motion',
    your_ticket: 'Your ticket',
    route_label: 'Your route',
    route_empty: 'No route yet — choose your 5',
    all_sites: 'All sites',
    r_unlocked: 'Unlocked',
    r_locked: 'Locked',
    pick_one: 'pick one',
    view_mode: 'View mode',
    view_list: 'List',
    view_map: 'Map',
    step_monument: 'Monument',
    step_museum: 'Museum',
    step_free: '3 free',
    recommend_full: '✦ Recommend all 5 for me',
    rec_head: 'Suggested for you',
    rec_sub: 'Ready-made valid 5-site sets, ranked for the weather & opening hours. Use one, or pick your own.',
    rec_badge: 'Recommended',
    use_set: 'Use this set',
    pick_own: 'Pick my own 5',
    back_sugg: '← See suggestions',
    reset_picks: '↺ Clear all',
    walk_time: (m) => `${m} min walk`,
    open_all: 'All 5 open now',
    n_closed: (n) => `${n} closed now`,
    quiet_pick: 'Includes a quiet spot',
    all_cats: 'All',
    route_walk: (d, m) => `${d} · ${m} min walk`,
    auto_free: 'Fill the last 3 for me',
    list_more: (n) => `Show ${n} more`,
    rank_dist: 'Sort by distance',
    pick_do: 'Pick',
    pick_remove: 'Remove',
    picked_lbl: '✓ Picked',
    build_done: 'Continue',
    done_title: 'Your journey',
    done_sub: 'Head to each site and check in to stamp it.',
    go_checkin: "Let's go!",
    edit_plan: 'Change picks',
    passport_title: 'My passport',
    lang_switch: 'Language',
    code_label: 'Your ticket code',
    stamps_of: (a, b) => `${a}/${b} stamps collected`,
    all_done: '🎉 Complete! You have checked in everywhere.',
    set_complete: 'You completed this stamp set!',
    redeem: '🎁 Redeem voucher',
    redeem_intro: 'Show this screen to a staff member at any ticket counter to receive a paper voucher.',
    staff_confirm: 'Staff confirm',
    enter_code: 'Enter staff code',
    wrong_code: 'Wrong code.',
    staff_only: 'Organizer area. Enter the staff code to continue.',
    redeemed: '✅ Voucher redeemed. Thank you!',
    wrong_wait: (n) => `Not quite. Read the sign again and retry in ${n}s.`,
    keep_code: 'Screenshot this code. It is the only way to get your passport back on a new phone or after clearing your browser.',
    install: '⬇️ Install the app (works offline)',
    install_why: 'Add it to your home screen to use it without a signal.',
    install_ios: 'On iPhone: tap Share ⬆️ then "Add to Home Screen".',
    // location & ticket counters
    locate_me: 'My location',
    reset_north: 'Face north',
    research_optin: 'Anonymous foot-traffic count to help spread visitors evenly — no path, time or identity stored. On by default; tap to turn off.',
    journey_optin: 'Join the journey study (optional): records the order of sites you visit in one trip, anonymously, so routes can be compared by nationality. Tap to join.',
    loc_note: '📍 Location and compass show where you are and which way you face — to check in and find the nearest ticket counter. We ask when you open the map.',
    study_note: 'The app also counts anonymous foot-traffic, helping organizers spread visitors more evenly across the sites.',
    hours_label: 'Hours',
    addr_label: 'Address',
    prev_site: 'Previous site',
    next_site: 'Next site',
    locating_now: 'Finding you…',
    booth_find: '🎟️ Nearest ticket counter',
    booth_hint: 'Claim vouchers or ask for help at a ticket counter.',
    booth_nearest: (name, d) => `Counter ${name} · ${d} away`,
    booth_dir: '➤ Directions to the counter',

    org_heat: 'Footfall heatmap (research)',
    org_heat_hint: 'Anonymous density from visitors who opted in to share location. Counts per ~150 m cell only, no path stored; cells under 5 are hidden.',
    org_heat_filter: 'Filter by nationality:',
    org_heat_all: 'All',
    org_lang: 'Language / nationality',
    org_lang_hint: 'A nationality proxy: the device locale and the language chosen on the welcome screen.',
    org_lang_device: 'Device locale',
    org_lang_pick: 'Chosen language',
    org_nat: 'Behaviour by nationality',
    org_nat_hint: 'Anonymous counts per behaviour, split by the language each visitor chose. Rows = site/step, columns = nationality.',
    org_nat_metric: 'Metric',
    org_nat_none: 'No per-nationality data yet.',
    org_journeys: 'Journeys (optional study)',
    org_journeys_hint: 'The order visitors walked their sites, per trip, only from visitors who opted in. Each session is an ephemeral id — nothing links across trips.',
    org_journeys_export: '⬇ Export journeys (CSV)',
    org_journeys_count: (n) => `${n} journey events logged`,
    org_events: 'Other events',
    org_flagged: 'Passports to review',
    org_flagged_none: 'Nothing unusual so far.',
    org_flagged_hint: 'Stamps that could not have been walked between. Advisory only. hand over the voucher if the visitor makes sense.',
    flag_warn: '⚠️ This passport has unusual check-in timing. Ask the visitor about a site or two before handing over the voucher. if they check out, redeem as normal.',

    // scoring & rewards
    points: 'points',
    earned: (n) => `+${n} points`,
    perfect_bonus: 'All correct first try',
    spotlight: 'Spotlight site',
    spotlight_hint: (n) => `Current spotlight. Checking in here earns +${n} bonus points.`,
    rank: 'Rank',
    no_rank: 'No rank yet',
    next_rank: (n, name) => `${n} more points to reach “${name}”`,
    rewards_title: 'Rewards',
    reward_locked: (n) => `Needs ${n} points`,
    reward_ready: 'Unlocked. Collect at any ticket counter',
    reward_taken: 'Collected',
    other_sites: 'Other sites',
    other_sites_hint: 'Still earn stamps and points, not part of a tour',
    claim: '🎁 Claim',
    score_how: 'How points work',
    pt_stamp: 'per check-in',
    pt_perfect: 'quiz answered correctly first try',
    pt_spotlight: 'checking in at a spotlight site',
    pt_tour: 'completing a tour (every stamp on it)',
    pt_all: (n) => `checking in at all ${n} sites`,
    tally_stamps: (n) => `${n} stamps collected`,
    tally_tours: (a, b) => `Tours completed ${a}/${b}`,
    tally_all: 'Full-set bonus',

    // backup & recovery
    backup_title: 'Backup & recovery',
    backup_hint:
      'Your passport is stored on this device. Note this code down. if you switch phones or clear your browser, it brings every stamp back.',
    your_code: 'Recovery code',
    copy: 'Copy',
    copied: 'Copied',
    copy_link: 'Copy backup link',
    restore: 'Restore from another code',
    restore_do: 'Restore',
    restore_ok: '✅ Passport restored.',
    restore_bad: 'The code is 8 characters.',
    restore_missing: 'No passport found for that code.',
    restore_offline: 'Could not reach the server. Try again when online.',
    offline_ok: 'Check-in works offline. your data uploads once you are back online.',
    ticket_points: 'Ticket counters',
    show_all_sites: 'Show all sites',

    // tours & map
    walk: (d, m) => `${d} · ~${m} min walk`,
    open_tour: 'Open tour →',
    popup_detail: 'Open & check in',
    popup_dir: 'Directions',
    stamped: 'Checked in',
    open_now: 'Open now',
    closed_now: 'Closed',
    closing_soon: (m) => `Closing in ${m} min`,
    opens_at: (t) => `Opens ${t}`,
    filter_open: 'Open now',
    closed_warning: 'This site is closed right now. you can still check in if you are at the spot.',

    // organizer dashboard
    org_title: 'Organizer dashboard',
    org_sub: 'Check-ins per destination',
    org_evenness: 'Evenness',
    org_total: 'Check-ins',
    org_covered: 'Sites visited',
    org_spotlight_now: 'Currently bonus-boosted',
    org_refresh: 'Refresh',
    org_export: '⬇ Export CSV',
    org_no_data: 'No check-ins yet. Numbers appear as soon as the first visitor checks in.',
    org_survey: 'Coordinates to re-survey',
    org_quiz_todo: 'Quiz banks still auto-generated',
    org_nearest_ticket: 'Nearest counter',
    org_traffic: 'Footfall (survey)',
    org_priority: 'Promo priority',
    lvl_low: 'low',
    lvl_medium: 'medium',
    lvl_high: 'high',
    org_updated: (t) => `Updated ${t}`,

    // content editor (organizer tier only)
    org_tier_volunteer: 'Volunteer (view only)',
    org_tier_admin: 'Organizer (can edit content)',
    org_edit: 'Edit content',
    org_edit_hint:
      'Edit here, download the JSON and hand it to the dev to replace src/lib/data/. Nothing is saved to the server. Edits are lost if you do not download.',
    org_need_admin: 'Editing content needs the organizer code. The volunteer code can only read the numbers.',
    org_tab_dest: 'Destinations',
    org_tab_tours: 'Tours',
    org_tab_rewards: 'Rewards',
    org_tab_event: 'About',
    org_tours_hint:
      'Stop order is the walking order. A destination can be in at most one tour; sites in no tour still earn stamps and points, they just are not a voucher set.',
    org_rewards_hint: (n) => `Point thresholds must ascend and cannot exceed ${n}, the score every visitor can be sure of reaching.`,
    org_event_hint: 'Home page copy.',
    org_add_tour: '+ Add tour',
    org_del_tour: 'Delete tour',
    org_add_stop: '+ Add stop',
    org_add_tier: '+ Add tier',
    org_del_tier: 'Delete tier',
    org_add_step: '+ Add step',
    org_del_step: 'Delete step',
    org_download_json: (f) => `⬇ Download ${f}`,
    org_load_json: 'Open an edited file',
    org_reset: 'Back to shipped version',
    org_reset_confirm: 'Discard every change you have not downloaded?',
    org_problems: (n) => `${n} problems - fix them before downloading`,
    org_data_ok: '✔ Data is valid',
    org_bad_file: (m) => `Could not read that file: ${m}`,
    org_add_q: '+ Add question',
    org_del_q: 'Delete',
    org_add_opt: '+ Add option',
    org_del_opt: 'Remove',
    org_answer: 'Correct answer',
    org_generated: 'auto-generated',
    org_reviewed: 'Mark reviewed',
    org_needs_survey: 'Coordinates need a survey',
    f_code: 'Code',
    f_name: 'Name',
    f_address: 'Address',
    f_hours: 'Opening hours',
    f_desc: 'Description',
    f_category: 'Category',
    f_radius: 'Radius (m)',
    f_question: 'Question',
    f_difficulty: 'Difficulty',
    f_title: 'Title',
    f_theme: 'Theme',
    f_voucher: 'Voucher',
    f_stops: 'Stops',
    f_points: 'Points',
    f_icon: 'Icon',
    f_reward: 'Reward',
    f_subtitle: 'Subtitle',
    f_tagline: 'Tagline',
    f_year: 'Year',
    f_venue: 'Venue',
    f_dates: 'Dates',
    f_intro: 'Intro',
    f_note: 'Note',
    f_steps: 'Steps',
    org_details: 'Details',
    lvl_easy: 'easy',
    lvl_hard: 'hard'
  }
};

export function s(key, ...args) {
  const v = UI[i18n.lang]?.[key] ?? UI.vi[key] ?? key;
  return typeof v === 'function' ? v(...args) : v;
}
