import { i18n } from './i18n.svelte.js';

// UI chrome strings (not content — content lives in the JSON data as { vi, en }).
const UI = {
  vi: {
    intro: 'Giới thiệu',
    explore: 'Khám phá',
    tours: 'Tuyến',
    passport: 'Hộ chiếu',
    sites_count: (n) => `${n} địa điểm trong phố cổ`,
    tap_hint: 'Chạm vào một điểm để xem chi tiết',
    all: 'Tất cả',
    no_sites: 'Chưa có điểm đến trong mục này.',
    how_it_works: 'Cách hoạt động',
    open_map: '🗺️ Khám phá bản đồ',
    see_tours: '🚶 Xem tuyến đi bộ',
    collected: (a, b) => `Bạn đã sưu tầm ${a}/${b} tem.`,
    view_passport: 'Xem hộ chiếu →',
    directions: '➤ Chỉ đường bằng Google Maps',
    checkin: '📍 Check-in tại đây',
    simulate: '🧪 Giả lập đã đến nơi (test)',
    locating: 'Đang xác định vị trí…',
    retry: 'Thử lại',
    far: (d, r) => `Bạn đang cách điểm đến khoảng ${d} m (cần ≤ ${r} m). Hãy đến gần hơn rồi thử lại.`,
    geo_denied: 'Bạn cần cho phép truy cập vị trí để check-in.',
    geo_fail: 'Không lấy được vị trí. Hãy thử lại ở ngoài trời.',
    arrived: '✔ Đã đến nơi! Trả lời câu hỏi để nhận tem:',
    question_of: (i, n) => `Câu ${i}/${n}`,
    wrong: 'Chưa đúng — thử lại nhé!',
    checkin_done: '✅ Đã check-in! Tem đã được thêm vào hộ chiếu.',
    tours_title: 'Tuyến đi bộ',
    tours_sub: 'Khám phá phố cổ theo chủ đề',
    stops: (n) => `${n} điểm dừng`,
    route: 'Lộ trình',
    passport_title: 'Hộ chiếu của tôi',
    stamps_of: (a, b) => `${a}/${b} tem đã sưu tầm`,
    not_yet: 'Chưa check-in',
    all_done: '🎉 Hoàn thành! Bạn đã check-in tất cả điểm đến.',
    set_complete: 'Đã hoàn thành bộ tem này!',
    redeem: '🎁 Đổi voucher',
    redeem_intro: 'Đưa màn hình này cho kiểm soát viên tại quầy vé để nhận voucher giấy.',
    staff_confirm: 'Kiểm soát viên xác nhận',
    enter_code: 'Nhập mã kiểm soát viên',
    confirm: 'Xác nhận',
    wrong_code: 'Mã không đúng.',
    redeemed: '✅ Đã đổi voucher. Cảm ơn bạn!'
  },
  en: {
    intro: 'About',
    explore: 'Explore',
    tours: 'Tours',
    passport: 'Passport',
    sites_count: (n) => `${n} sites in the Ancient Town`,
    tap_hint: 'Tap a point to see details',
    all: 'All',
    no_sites: 'No sites in this category yet.',
    how_it_works: 'How it works',
    open_map: '🗺️ Explore the map',
    see_tours: '🚶 Walking tours',
    collected: (a, b) => `You have collected ${a}/${b} stamps.`,
    view_passport: 'View passport →',
    directions: '➤ Directions in Google Maps',
    checkin: '📍 Check in here',
    simulate: '🧪 Simulate arrival (test)',
    locating: 'Locating you…',
    retry: 'Try again',
    far: (d, r) => `You are about ${d} m away (need ≤ ${r} m). Get closer and try again.`,
    geo_denied: 'Please allow location access to check in.',
    geo_fail: 'Could not get your location. Try again outdoors.',
    arrived: '✔ You are here! Answer the questions to earn a stamp:',
    question_of: (i, n) => `Question ${i}/${n}`,
    wrong: 'Not quite — try again!',
    checkin_done: '✅ Checked in! The stamp was added to your passport.',
    tours_title: 'Walking tours',
    tours_sub: 'Explore the old town by theme',
    stops: (n) => `${n} stops`,
    route: 'Route',
    passport_title: 'My passport',
    stamps_of: (a, b) => `${a}/${b} stamps collected`,
    not_yet: 'Not checked in',
    all_done: '🎉 Complete! You have checked in everywhere.',
    set_complete: 'You completed this stamp set!',
    redeem: '🎁 Redeem voucher',
    redeem_intro: 'Show this screen to a staff member at any ticket counter to receive a paper voucher.',
    staff_confirm: 'Staff confirm',
    enter_code: 'Enter staff code',
    confirm: 'Confirm',
    wrong_code: 'Wrong code.',
    redeemed: '✅ Voucher redeemed. Thank you!'
  }
};

export function s(key, ...args) {
  const v = UI[i18n.lang]?.[key] ?? UI.vi[key] ?? key;
  return typeof v === 'function' ? v(...args) : v;
}
