// Translation intake: content/translate-<lang>.tsv -> the data files + a UI locale.
//
//   node scripts/i18n-import.mjs ko zh ja th fr de     (or no args = every tsv found)
//
// The TSV is what scripts/i18n-export.mjs handed the translator: three columns,
//   file::path <TAB> vietnamese <TAB> translation
// The path is authoritative, so nothing is matched on the Vietnamese string and a
// re-run is idempotent. Rows whose text is empty are skipped (still to translate).
//
//   destinations.json::[3].short          -> adds { …, ko: "…" } to that node
//   strings.js::checkin                   -> src/lib/i18n/ko.js
//   strings.js::question_of()             -> same file, as a function, {i} -> ${i}
//
// The runtime needs nothing else: t() reads field[lang] ?? field.vi and s() reads
// UI[lang]?.[key] ?? UI.vi[key], so a language appears as soon as its data is here.
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(root, 'src/lib/data');
const LOCALES = join(root, 'src/lib/i18n');

const args = process.argv.slice(2);
const langs = args.length
  ? args
  : readdirSync(join(root, 'content'))
      .map((f) => /^translate-(\w+)\.tsv$/.exec(f)?.[1])
      .filter(Boolean);

/** walk `[3].quizBank[0].options[2]` down an object */
const at = (obj, path) => {
  let cur = obj;
  for (const seg of path.match(/[^.[\]]+/g) ?? []) {
    if (cur == null) return null;
    cur = cur[/^\d+$/.test(seg) ? Number(seg) : seg];
  }
  return cur;
};

for (const lang of langs) {
  const tsv = join(root, `content/translate-${lang}.tsv`);
  if (!existsSync(tsv)) { console.error(`no content/translate-${lang}.tsv`); continue; }

  // path <TAB> vietnamese <TAB> translation — column 3 is the only one read
  const rows = readFileSync(tsv, 'utf8').split('\n').slice(1)
    .map((l) => l.split('\t'))
    .filter(([p, , text]) => p?.includes('::') && text?.trim())
    .map(([p, , text]) => {
      const [file, ...rest] = p.split('::');
      return { file, path: rest.join('::'), text: text.trim() };
    });

  const files = new Map();       // data file -> parsed json
  const ui = new Map();          // strings.js key -> text
  let content = 0, missing = [];

  for (const r of rows) {
    if (r.file === 'strings.js') { ui.set(r.path, r.text); continue; }
    if (r.file === 'languages.js') continue; // greetings are already in their own language
    if (!files.has(r.file)) files.set(r.file, JSON.parse(readFileSync(join(DATA, r.file), 'utf8')));
    const node = at(files.get(r.file), r.path);
    if (node == null || typeof node.vi !== 'string') { missing.push(`${r.file}::${r.path}`); continue; }
    node[lang] = r.text;
    content++;
  }

  for (const [file, json] of files) {
    writeFileSync(join(DATA, file), `${JSON.stringify(json, null, 2)}\n`);
  }

  if (ui.size) {
    mkdirSync(LOCALES, { recursive: true });
    // merge: a worksheet usually carries only the rows still missing, so anything
    // already in the locale file has to survive the run
    const out = join(LOCALES, `${lang}.js`);
    if (existsSync(out)) {
      const prev = readFileSync(out, 'utf8');
      for (const m of prev.matchAll(/^ {2}(\w+): `((?:\\.|[^`])*)`,$/gm)) if (!ui.has(m[1])) ui.set(m[1], m[2]);
      for (const m of prev.matchAll(/^ {2}(\w+): \([^)]*\) => `((?:\\.|[^`])*)`,$/gm)) if (!ui.has(`${m[1]}()`)) ui.set(`${m[1]}()`, m[2].replace(/\$\{(\w+)\}/g, '{$1}'));
    }
    const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    const lines = [];
    for (const [key, text] of ui) {
      if (key.endsWith('()')) {
        // "Câu {i}/{n}" -> (i, n) => `Câu ${i}/${n}`, args in first-seen order
        const slots = [...new Set([...text.matchAll(/\{(\w+)\}/g)].map((m) => m[1]))];
        const body = esc(text).replace(/\{(\w+)\}/g, (_, s) => `\${${s}}`);
        lines.push(`  ${key.slice(0, -2)}: (${slots.join(', ')}) => \`${body}\`,`);
      } else {
        lines.push(`  ${key}: \`${esc(text)}\`,`);
      }
    }
    writeFileSync(join(LOCALES, `${lang}.js`),
      `// ${lang} UI strings — generated by scripts/i18n-import.mjs from\n` +
      `// content/translate-${lang}.tsv. Edit the TSV, not this file.\n` +
      `export default {\n${lines.join('\n')}\n};\n`);
  }

  console.log(`${lang}: ${content} content strings, ${ui.size} UI strings` +
    (missing.length ? `  — ${missing.length} unknown paths: ${missing.slice(0, 3).join(', ')}` : ''));
}
